import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/app_provider.dart';

String tr(BuildContext context, String key, [Map<String, String>? args]) {
  AppProvider prov;
  try {
    prov = Provider.of<AppProvider>(context);
  } catch (_) {
    // In some contexts (event handlers) listening is not allowed. Fall back to
    // a non-listening lookup so tr() can be used from callbacks.
    prov = Provider.of<AppProvider>(context, listen: false);
  }
  final lang = prov.language;

  const Map<String, Map<String, String>> translations = {
    'en': {
      'feed': 'Feed',
      'login_register': 'Login / Register',
      'username': 'Username',
      'password': 'Password',
      'username_hint': 'Enter your username',
      'password_hint': 'Enter your password',
      'remember_user': 'Remember user',
      'login': 'Login',
      'register': 'Register',
      'app_name': 'InstaDAM',
      'app_loading': 'Loading application',
      'logging_in': 'Signing in...',
      'registering': 'Creating account...',
      'enter_username': 'Enter your username',
      'enter_password': 'Enter your password',
      'username_min_chars': 'Username must have at least 3 characters',
      'password_min_chars': 'Password must have at least 6 characters',
      'dont_have_account': 'Do not have an account? Register',
      'have_account': 'Already have an account? Login',
      'forgot_password': 'Forgot password?',
      'forgot_password_not_impl': 'Password recovery is not available yet',
      'settings': 'Settings',
      'dark_mode': 'Dark mode',
      'notifications': 'Notifications',
      'language': 'Language:',
      'export_db': 'Export database to JSON',
      'import_db': 'Import database from Documents/insta_export.json',
      'profile': 'Profile',
      'edit': 'Edit',
      'no_name': 'No name',
      'exported_to': 'Exported to {path} ({bytes} bytes)',
      'export_failed': 'Export failed: {err}',
      'no_import_file': 'No import file found in Documents',
      'import_completed': 'Import completed',
      'import_failed': 'Import failed: {err}',
      'post': 'Post',
      'likes': '{n} likes',
      'no_comments': 'No comments',
      'no_posts': 'No posts yet',
      'enter_description': 'Enter a description',
      'published': 'Published',
      'create_post': 'Create post',
      'description': 'Description',
      'publish': 'Publish',
      'create_post_description_label_required': 'Description (required)',
      'create_post_description_field_label': 'Post description field',
      'create_post_description_field_hint': 'Type the description for the post',
      'create_post_description_error_required': 'Description is required',
      'create_post_image_selector_no_image':
          'Image selector. No image selected',
      'create_post_image_selector_with_image': 'Image selector. Image selected',
      'create_post_image_selector_hint': 'Double tap to choose an image',
      'create_post_publishing': 'Publishing post',
      'create_post_published_announcement': 'Post published successfully',
      'create_post_publish_hint': 'Double tap to publish the post',
      'create_post_loading_hint': 'Publishing in progress, please wait',
      'invalid_credentials': 'Invalid credentials',
      'user_exists': 'User already exists',
      'save': 'Save',
      'logout': 'Logout',
      'export': 'Export',
      'import': 'Import',
      'time_now': 'just now',
      'time_minutes_ago': '{n} minutes ago',
      'time_hours_ago': '{n} hours ago',
      'time_days_ago': '{n} days ago',
      'unknown_user': 'Unknown user',
      'no_description': 'No description',
      'post_image_no_description': 'Post image without description',
      'post_image_description': 'Post image: {desc}',
      'post_summary':
          'Post by {author}, {time}. {description}. {likes} likes and {comments} comments.',
      'open_post_details': 'Double tap to open post details and comments',
      'post_options': 'Post options',
      'post_deleted': 'Post deleted',
      'like_action': 'Like',
      'unlike_action': 'Remove like',
      'like_hint': 'Double tap to change like state',
      'liked_announcement': 'Like added. Now {n} likes.',
      'unliked_announcement': 'Like removed. Now {n} likes.',
      'like_requires_login': 'Sign in to like posts',
      'comments_count_button': '{n} comments',
      'open_comments': 'Double tap to open comments',
      'go_back': 'Go back',
      'open_profile': 'Open profile',
      'open_settings': 'Open settings',
      'loading_feed': 'Loading feed',
      'feed_empty_announcement': 'Feed is empty, no posts available',
      'create_post_button': 'Create post',
      'loading_comments': 'Loading comments',
      'post_detail_summary':
          '{description}. {likes} likes and {comments} comments.',
      'comment_item_semantics': 'Comment by {user}, {time}: {text}',
      'comment_field_label': 'Comment text field',
      'comment_field_visible_label': 'Comment',
      'add_comment_hint': 'Add comment',
      'send_comment_button': 'Send comment',
      'send_comment_hint': 'Double tap to send comment',
      'comment_added': 'Comment added',
      'comment_added_with_count': 'Comment added. Now {n} comments.',
    },
    'es': {
      'feed': 'Feed',
      'login_register': 'Login / Registro',
      'username': 'Usuario',
      'password': 'Contraseña',
      'username_hint': 'Introduce tu usuario',
      'password_hint': 'Introduce tu contraseña',
      'remember_user': 'Recordar usuario',
      'login': 'Iniciar sesión',
      'register': 'Registrarse',
      'app_name': 'InstaDAM',
      'app_loading': 'Cargando aplicacion',
      'logging_in': 'Iniciando sesión...',
      'registering': 'Creando cuenta...',
      'enter_username': 'Introduce el usuario',
      'enter_password': 'Introduce la contraseña',
      'username_min_chars': 'El usuario debe tener al menos 3 caracteres',
      'password_min_chars': 'La contraseña debe tener al menos 6 caracteres',
      'dont_have_account': 'No tienes cuenta? Regístrate',
      'have_account': 'Ya tienes cuenta? Inicia sesión',
      'forgot_password': 'He olvidado mi contraseña',
      'forgot_password_not_impl':
          'La recuperación de contraseña aún no está disponible',
      'settings': 'Ajustes',
      'dark_mode': 'Modo oscuro',
      'notifications': 'Notificaciones',
      'language': 'Idioma:',
      'export_db': 'Exportar BD a JSON',
      'import_db': 'Importar BD desde Documents/insta_export.json',
      'profile': 'Perfil',
      'edit': 'Editar',
      'no_name': 'Sin nombre',
      'exported_to': 'Exportado a {path} ({bytes} bytes)',
      'export_failed': 'Error exportando: {err}',
      'no_import_file': 'No se encontró archivo de importación en Documents',
      'import_completed': 'Importación completada',
      'import_failed': 'Error importando: {err}',
      'post': 'Publicación',
      'likes': '{n} me gusta',
      'no_comments': 'No hay comentarios',
      'no_posts': 'Sin publicaciones aún',
      'enter_description': 'Introduce una descripción',
      'published': 'Publicado',
      'create_post': 'Crear publicación',
      'description': 'Descripción',
      'publish': 'Publicar',
      'create_post_description_label_required': 'Descripción (obligatoria)',
      'create_post_description_field_label':
          'Campo de descripción de la publicación',
      'create_post_description_field_hint':
          'Escribe la descripción de la publicación',
      'create_post_description_error_required': 'La descripción es obligatoria',
      'create_post_image_selector_no_image':
          'Selector de imagen. No hay imagen seleccionada',
      'create_post_image_selector_with_image':
          'Selector de imagen. Imagen seleccionada',
      'create_post_image_selector_hint': 'Doble toque para elegir una imagen',
      'create_post_publishing': 'Publicando publicación',
      'create_post_published_announcement':
          'Publicación publicada correctamente',
      'create_post_publish_hint': 'Doble toque para publicar la publicación',
      'create_post_loading_hint': 'Publicacion en progreso, espera por favor',
      'invalid_credentials': 'Credenciales inválidas',
      'user_exists': 'Usuario ya existe',
      'save': 'Guardar',
      'logout': 'Cerrar sesión',
      'export': 'Exportar',
      'import': 'Importar',
      'time_now': 'justo ahora',
      'time_minutes_ago': 'hace {n} minutos',
      'time_hours_ago': 'hace {n} horas',
      'time_days_ago': 'hace {n} dias',
      'unknown_user': 'Usuario desconocido',
      'no_description': 'Sin descripcion',
      'post_image_no_description': 'Imagen de la publicacion sin descripcion',
      'post_image_description': 'Imagen de la publicacion: {desc}',
      'post_summary':
          'Publicacion de {author}, {time}. {description}. {likes} me gusta y {comments} comentarios.',
      'open_post_details': 'Doble toque para abrir detalles y comentarios',
      'post_options': 'Opciones de la publicacion',
      'post_deleted': 'Publicacion eliminada',
      'like_action': 'Dar me gusta',
      'unlike_action': 'Quitar me gusta',
      'like_hint': 'Doble toque para cambiar el estado de me gusta',
      'liked_announcement': 'Me gusta anadido. Ahora hay {n} me gusta.',
      'unliked_announcement': 'Me gusta quitado. Ahora hay {n} me gusta.',
      'like_requires_login': 'Inicia sesion para dar me gusta',
      'comments_count_button': '{n} comentarios',
      'open_comments': 'Doble toque para abrir comentarios',
      'go_back': 'Volver',
      'open_profile': 'Abrir perfil',
      'open_settings': 'Abrir ajustes',
      'loading_feed': 'Cargando feed',
      'feed_empty_announcement': 'El feed esta vacio, no hay publicaciones',
      'create_post_button': 'Crear publicacion',
      'loading_comments': 'Cargando comentarios',
      'post_detail_summary':
          '{description}. {likes} me gusta y {comments} comentarios.',
      'comment_item_semantics': 'Comentario de {user}, {time}: {text}',
      'comment_field_label': 'Campo de texto de comentario',
      'comment_field_visible_label': 'Comentario',
      'add_comment_hint': 'Anadir comentario',
      'send_comment_button': 'Enviar comentario',
      'send_comment_hint': 'Doble toque para enviar comentario',
      'comment_added': 'Comentario anadido',
      'comment_added_with_count':
          'Comentario anadido. Ahora hay {n} comentarios.',
    },
  };

  var s = translations[lang]?[key] ?? translations['en']?[key] ?? key;
  if (args != null) {
    args.forEach((k, v) {
      s = s.replaceAll('{$k}', v);
    });
  }
  return s;
}
